# Generated by Django 4.2.5 on 2024-02-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kecamatan",
            name="kota",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="kecamatan", to="locations.kota"
            ),
        ),
        migrations.AlterField(
            model_name="kelurahan",
            name="kecamatan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="kelurahan", to="locations.kecamatan"
            ),
        ),
        migrations.AlterField(
            model_name="kota",
            name="provinsi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="kota", to="locations.provinsi"
            ),
        ),
    ]
