# Generated by Django 4.2.5 on 2024-02-15 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_alter_kecamatan_kota_alter_kelurahan_kecamatan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kelurahan",
            name="kecamatan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kelurahan",
                to="locations.kecamatan",
            ),
        ),
    ]
