# Generated by Django 4.2.5 on 2024-02-15 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_alter_kelurahan_kecamatan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kelurahan",
            options={"ordering": ("created",)},
        ),
    ]
