# Generated by Django 4.2.5 on 2024-02-22 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_tingkatdua_tingkatsatu_tingkattiga_tingkatempat_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kecamatan",
            options={"ordering": ("-created",), "verbose_name_plural": "Kecamatan"},
        ),
        migrations.AlterModelOptions(
            name="kelurahan",
            options={"ordering": ("created",), "verbose_name_plural": "Kelurahan"},
        ),
        migrations.AlterModelOptions(
            name="kota",
            options={"ordering": ("-created",), "verbose_name_plural": "Kota"},
        ),
        migrations.AlterModelOptions(
            name="provinsi",
            options={"ordering": ("-created",), "verbose_name_plural": "Provinsi"},
        ),
    ]
