# Generated by Django 4.2.5 on 2024-02-15 03:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tps",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("psu", models.CharField(blank=True, null=True)),
                ("ts", models.DateTimeField(blank=True, null=True)),
                ("status_suara", models.BooleanField(default=False)),
                ("status_adm", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images/")),
                (
                    "tps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="duanolduaempat.tps"
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("count", models.IntegerField(blank=True, null=True)),
                (
                    "tps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="charts", to="duanolduaempat.tps"
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Administration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("suara_sah", models.IntegerField(blank=True, null=True)),
                ("suara_total", models.IntegerField(blank=True, null=True)),
                ("pemilih_dpt_l", models.IntegerField(blank=True, null=True)),
                ("pemilih_dpt_p", models.IntegerField(blank=True, null=True)),
                ("pengguna_dpt_j", models.IntegerField(blank=True, null=True)),
                ("pengguna_dpt_l", models.IntegerField(blank=True, null=True)),
                ("pengguna_dpt_p", models.IntegerField(blank=True, null=True)),
                ("pengguna_dptb_j", models.IntegerField(blank=True, null=True)),
                ("pengguna_dptb_l", models.IntegerField(blank=True, null=True)),
                ("pengguna_dptb_p", models.IntegerField(blank=True, null=True)),
                ("suara_tidak_sah", models.IntegerField(blank=True, null=True)),
                ("pengguna_total_j", models.IntegerField(blank=True, null=True)),
                ("pengguna_total_l", models.IntegerField(blank=True, null=True)),
                ("pengguna_total_p", models.IntegerField(blank=True, null=True)),
                ("pengguna_non_dpt_j", models.IntegerField(blank=True, null=True)),
                ("pengguna_non_dpt_l", models.IntegerField(blank=True, null=True)),
                ("pengguna_non_dpt_p", models.IntegerField(blank=True, null=True)),
                (
                    "tps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrations",
                        to="duanolduaempat.tps",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
