# Generated by Django 4.2.5 on 2024-02-15 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("duanolduaempat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyDetection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "tps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="anomalies", to="duanolduaempat.tps"
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
