# Generated by Django 4.2.5 on 2024-02-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duanolduaempat", "0002_anomalydetection"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomalydetection",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
