# Generated by Django 4.2.5 on 2024-02-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duanolduaempat", "0004_anomalydetection_is_reported_chart_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="tps",
            name="has_anomaly",
            field=models.BooleanField(default=False),
        ),
    ]
