# Generated by Django 4.2.5 on 2024-02-17 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_alter_kelurahan_options"),
        ("duanolduaempat", "0005_tps_has_anomaly"),
    ]

    operations = [
        migrations.AddField(
            model_name="tps",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tps",
                to="locations.provinsi",
            ),
        ),
    ]
