# Generated by Django 4.2.5 on 2024-02-17 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_alter_kelurahan_options"),
        ("duanolduaempat", "0006_tps_province"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("total_suara", models.IntegerField(blank=True, null=True)),
                ("total_tps", models.IntegerField(blank=True, null=True)),
                ("paslon_satu", models.IntegerField(blank=True, null=True)),
                ("paslon_dua", models.IntegerField(blank=True, null=True)),
                ("paslon_tiga", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ReportDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("total_suara", models.IntegerField(blank=True, null=True)),
                ("total_tps", models.IntegerField(blank=True, null=True)),
                ("paslon_satu", models.IntegerField(blank=True, null=True)),
                ("paslon_dua", models.IntegerField(blank=True, null=True)),
                ("paslon_tiga", models.IntegerField(blank=True, null=True)),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="locations.provinsi",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="details", to="duanolduaempat.report"
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
