# Generated by Django 4.2.5 on 2024-02-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duanolduaempat", "0007_report_reportdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="administration",
            name="ts",
            field=models.DateTimeField(blank=True, null=True, verbose_name="version"),
        ),
        migrations.AddField(
            model_name="chart",
            name="ts",
            field=models.DateTimeField(blank=True, null=True, verbose_name="version"),
        ),
        migrations.AddField(
            model_name="image",
            name="ts",
            field=models.DateTimeField(blank=True, null=True, verbose_name="version"),
        ),
        migrations.AlterField(
            model_name="tps",
            name="has_anomaly",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tps",
            name="ts",
            field=models.DateTimeField(blank=True, null=True, verbose_name="version"),
        ),
    ]
