# Generated by Django 4.2.5 on 2024-02-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duanolduaempat", "0011_alter_tps_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupchasil",
            name="filename",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
