# Generated by Django 4.2.5 on 2024-02-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duanolduaempat", "0012_backupchasil_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="is_backup",
            field=models.BooleanField(default=False),
        ),
    ]
