# Generated by Django 4.2.5 on 2024-02-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_alter_kecamatan_options_alter_kelurahan_options_and_more"),
        ("duanolduaempat", "0014_tps_kelurahan"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="kecamatan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="locations.kecamatan",
            ),
        ),
    ]
