# Generated by Django 4.2.5 on 2024-02-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duanolduaempat", "0016_remove_image_kecamatan_image_kelurahan"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="total_suara_h_3",
            field=models.IntegerField(blank=True, null=True, verbose_name="Total Suara Hal. 3"),
        ),
        migrations.AddField(
            model_name="reportdetail",
            name="total_suara_h_3",
            field=models.IntegerField(blank=True, null=True, verbose_name="Total Suara Hal. 3"),
        ),
        migrations.AlterField(
            model_name="report",
            name="total_suara",
            field=models.IntegerField(blank=True, null=True, verbose_name="Total Suara Hal. 2"),
        ),
        migrations.AlterField(
            model_name="reportdetail",
            name="total_suara",
            field=models.IntegerField(blank=True, null=True, verbose_name="Total Suara Hal. 3"),
        ),
    ]
