# Generated by Django 4.2.5 on 2024-02-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duanolduaempat", "0017_report_total_suara_h_3_reportdetail_total_suara_h_3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportdetail",
            name="total_suara",
            field=models.IntegerField(blank=True, null=True, verbose_name="Total Suara Hal. 2"),
        ),
    ]
