# Generated by Django 4.2.5 on 2024-03-04 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_alter_kecamatan_options_alter_kelurahan_options_and_more"),
        ("duanolduaempat", "0018_alter_reportdetail_total_suara"),
    ]

    operations = [
        migrations.CreateModel(
            name="TpsSisa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("psu", models.CharField(blank=True, null=True)),
                ("ts", models.DateTimeField(blank=True, null=True, verbose_name="version")),
                ("status_suara", models.BooleanField(default=False)),
                ("status_adm", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True, null=True)),
                ("has_anomaly", models.BooleanField(default=True)),
                (
                    "kelurahan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sisa_tps",
                        to="locations.kelurahan",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sisa_tps",
                        to="locations.provinsi",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "TPS Sisa",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ChartSisa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("count", models.IntegerField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("ts", models.DateTimeField(blank=True, null=True, verbose_name="version")),
                (
                    "tps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sisa_charts",
                        to="duanolduaempat.tpssisa",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="AdministrationSisa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("ts", models.DateTimeField(blank=True, null=True, verbose_name="version")),
                ("suara_sah", models.IntegerField(blank=True, null=True)),
                ("suara_total", models.IntegerField(blank=True, null=True)),
                ("pemilih_dpt_l", models.IntegerField(blank=True, null=True)),
                ("pemilih_dpt_p", models.IntegerField(blank=True, null=True)),
                ("pengguna_dpt_j", models.IntegerField(blank=True, null=True)),
                ("pengguna_dpt_l", models.IntegerField(blank=True, null=True)),
                ("pengguna_dpt_p", models.IntegerField(blank=True, null=True)),
                ("pengguna_dptb_j", models.IntegerField(blank=True, null=True)),
                ("pengguna_dptb_l", models.IntegerField(blank=True, null=True)),
                ("pengguna_dptb_p", models.IntegerField(blank=True, null=True)),
                ("suara_tidak_sah", models.IntegerField(blank=True, null=True)),
                ("pengguna_total_j", models.IntegerField(blank=True, null=True)),
                ("pengguna_total_l", models.IntegerField(blank=True, null=True)),
                ("pengguna_total_p", models.IntegerField(blank=True, null=True)),
                ("pengguna_non_dpt_j", models.IntegerField(blank=True, null=True)),
                ("pengguna_non_dpt_l", models.IntegerField(blank=True, null=True)),
                ("pengguna_non_dpt_p", models.IntegerField(blank=True, null=True)),
                (
                    "tps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sisa_administrations",
                        to="duanolduaempat.tpssisa",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
